### ISSUE TITLE
Nginx-Proxy-Manager-JC21: Update needed

### ISSUE THREAD

**Issue by gnumanx** [chrizzo84/unraid-templates#2]
Thank you for your useful template!

To obtain any Let's Encrypt certificate I needed to update pip and the acme, certbot and certbot-dns-cloudflare components.

I entered the console and written:

`pip install --update pip`
`pip install --update acme`
`pip install --update certbot`
`pip install --update certbot-dns-cloudflare`

**Comment by chrizzo84** [comment]
Hi @gnumanx , this is the unmodified image of JC21 - I have deliberately not made any updates or similar customising on it. There are other Nginx Proxy Manager templates in the Unraid Appstore, unfortunately they are a few versions behind - that's why I took the JC21 directly, without any changes. Would you really like a custom image of JC21? If yes, I can have a look into it.

**Comment by gnumanx** [comment]
I need a reverse proxy on unraid. I struggled for a long while to find the best Caddy configuration. But I couldn't wait more, so I decided to use NPM. I am not happy with using it because there are claims of many serious CVE unresolved, but it works.
